--- 
:consumer_secret: aAP8NO6PvhXOnuPr6EBa0Ftn76h5P7utyMNn5vMJdYU
:company_alias: weemagine
:access_token: Bjo3YONTtvipLghWbYg1qw
:access_token_secret: F6Pr1YsLdxfxhLhsISGYyWKPlCABLmYmrYePQEiYo
:consumer_key: TJ8nPCqSqxmmDuzXhk2tdQ